---
title: "Development"
output: rmarkdown::html_vignette
date: "`r Sys.Date()`"
vignette: >
  %\VignetteIndexEntry{Development}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Notes on the RNAsum Rmd structure for developers

### `ref_dataset.list`

Processed data with following elements:

| Element                                        | Description                                                                                                                                                                            |
| ---------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `[[dataset]][["combined_data"]]`               | combined read count data (ref + sample datasets) (`combineDatasets` output in chunk `load_ref_data`)                                                                                   |
| `[[dataset]][["sample_annot"]]`                | combined data samples annotation ("combineDatasets()" output in chunk "load_ref_data")                                                                                                 |
| `[[dataset]][["clinical_info"]]`               | clinical (survival + treatment) info                                                                                                                                                   |
| `[[dataset]][["combined_data_processed"]]`     | transformed, filtered and normalised data (chunks "data_transformation" and "data_normalisation")                                                                                      |
| `[[dataset]][["batch_effect_corrected"]]`      | transformed, filtered, normalised and batch effect corrected data (chunk "batch_effect_correction")                                                                                    |
| `[[dataset]][["pca_combined_data_processed"]]` | PCA results for combined data                                                                                                                                                          |
| `[[dataset]][["pca_batch_effect_corrected"]]`  | PCA results for batch-effect corrected data                                                                                                                                            |
| `[[dataset]][["rle_combined_data_processed"]]` | RLE plot for combined data                                                                                                                                                             |
| `[[dataset]][["rle_batch_effect_corrected"]]`  | RLE plot for batch-effect corrected data                                                                                                                                               |
| `[[dataset]][["data_to_report"]]`              | fully combined and processed data for reporting                                                                                                                                        |
| `[[dataset]][["gene_annot_all"]]`              | gene annotation for combined read count data, containing all input genes. Includes SYMBOL, GENEBIOTYPE, ENSEMBL, SEQNAME, GENESEQSTART, and GENESEQEND. ENSEMBL is used for rownames.  |
| `[[dataset]][["gene_annot"]]`                  | gene annotation for transformed, filtered and normalised data. Includes SYMBOL, GENEBIOTYPE, ENSEMBL, SEQNAME, GENESEQSTART, GENESEQEND. SYMBOL is used for rownames.                  |
| `[[dataset]][["expr_mut_cn_data_all"]]`        | combined expression, mutation and CN data.                                                                                                                                             |
| `[[dataset]][["expr_mut_cn_data"]]`            | combined expression, mutation and CN data limited to cancer genes that meet user-defined CN values threshold.                                                                          |

### `ref_genes.list`

Genes of interest with following gene sets:

| Element                | Description                                                                                                                                                                                                                                 |
| ---------------------- | -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------   |
| `[["genes_cancer"]]`   | list of cancer genes derived from UMCCR Cancer Gene list (<https://github.com/vladsaveliev/NGS_Utils/blob/master/ngs_utils/reference_data/key_genes/umccr_cancer_genes.2019-03-20.tsv>) and OncoKB portal (http://oncokb.org/#/cancerGenes) |
| `[["genes_oncokb"]]`   | list of cancer genes derived from OncoKB only (although genes present in the UMCCR panel are also flagged)                                                                                                                                  |
| `[["genes_immune"]]`   | list of immune reponse markers provided in the "An Immunogram for the Cancer-Immunity Cycle" paper by Karasaki at al (2017) (https://www.ncbi.nlm.nih.gov/pubmed/28088513) and OmniSeq report (https://www.omniseq.com/)                    |
| `[["genes_hrd"]]`      | list of hrd genes                                                                                                                                                                                                                           |
| `[["pcgr"]]`           | list and PCGR annotation of indels                                                                                                                                                                                                          |
| `[["purple"]]`         | list and PURPLE annotation of CN altered genes                                                                                                                                                                                              |
| `[["manta"]]`          | list and Manta annotation of SVs                                                                                                                                                                                                            |
| `[["arriba"]]`         | list and Arriba annotation of gene fusion events                                                                                                                                                                                            |
| `[["pizzly"]]`         | list and Pizzly annotation of gene fusion events                                                                                                                                                                                            |
| `[["summary"]]`        | summary of above-mentioned gene lists, also used for expression summary tables and plots.                                                                                                                                                   |
