# Generated by roxytest: Do not edit by hand!

# File R/sample_data.R: @testexamples

test_that("Function read_sample_data() @ L28", {
  
  p <- list(
    dragen_rnaseq = system.file("rawdata/test_data/dragen", package = "RNAsum"),
    arriba_pdf = system.file("rawdata/test_data/dragen/arriba/fusions.pdf", package = "RNAsum"),
    arriba_tsv = system.file("rawdata/test_data/dragen/arriba/fusions.tsv", package = "RNAsum"),
    dragen_fusions = system.file(
      "rawdata/test_data/dragen/test_sample_WTS.fusion_candidates.final",
      package = "RNAsum"
    )
  )
  res <- read_sample_data(p, tempdir())
  expect_equal(length(res), 5)
  expect_null(res$salmon)
})

