# Generated by roxytest: Do not edit by hand!

# File R/refdata.R: @testexamples

test_that("Function get_refgenes() @ L55", {
  
  p <- list(
    genes_cancer = system.file("rawdata/genes/umccr_cancer_genes.2019-03-20.tsv",
      package = "RNAsum"
    ),
    genes_oncokb = system.file(
      "rawdata/OncoKB/CancerGenesList.txt",
      package = "RNAsum"
    ),
    civic_var_summaries = system.file(
      "rawdata/CIViC/01-Oct-2018-VariantSummaries.tsv",
      package = "RNAsum"
    )
  )
  x <- get_refgenes(p)
  expect_equal(nrow(x[["genes_cancer"]]), 1248)
})

