# Generated by roxytest: do not edit by hand!

# File R/qc_dragen.R: @testexamples

test_that("Function dragen_mapping_metrics_read() @ L17", {
  
  x <- system.file("rawdata/test_data/dragen",
    "test.mapping_metrics.csv",
    package = "RNAsum"
  )
  (d1 <- dragen_mapping_metrics_read(x))
  expect_equal(colnames(d1)[ncol(d1)], "pct")
  expect_equal(colnames(d1)[1], "category")
  expect_null(dragen_mapping_metrics_read(NULL))
})

