# Generated by roxytest: Do not edit by hand!

# File R/arriba.R: @testexamples

test_that("Function arriba_read_tsv() @ L14", {
  
  x <- system.file("rawdata/test_data/dragen/arriba/fusions.tsv", package = "RNAsum")
  (a <- arriba_read_tsv(x))
  expect_equal(colnames(a)[ncol(a)], "read_identifiers")
  expect_null(arriba_read_tsv(x = NULL))
})


test_that("Function arriba_read_pdf() @ L48", {
  
  pdf <- system.file("rawdata/test_data/dragen/arriba/fusions.pdf", package = "RNAsum")
  tsv <- system.file("rawdata/test_data/dragen/arriba/fusions.tsv", package = "RNAsum")
  fusions <- arriba_read_tsv(tsv)
  (pngs <- arriba_read_pdf(pdf, fusions, tempdir()))
  expect_equal(nrow(pngs), 4)
  expect_null(arriba_read_pdf(pdf = NULL))
})

