# Generated by roxytest: do not edit by hand!

# File R/refdata.R: @testexamples

test_that("Function get_refgenes() @ L57", {
  
  p <- list(
    genes_cancer = system.file("extdata/genes/umccr_cancer_genes.2019-03-20.tsv.gz",
      package = "RNAsum.data"
    ),
    genes_oncokb = system.file(
      "extdata/OncoKB/CancerGenesList.txt.gz",
      package = "RNAsum.data"
    ),
    civic_var_summaries = system.file(
      "extdata/CIViC/01-Oct-2018-VariantSummaries.tsv.gz",
      package = "RNAsum.data"
    )
  )
  x <- get_refgenes(p)
  expect_equal(nrow(x[["genes_cancer"]]), 1248)
})

