# Generated by roxytest: do not edit by hand!

# File R/clinical_info.R: @testexamples

test_that("Function clinical_info_read() @ L15", {
  
  x <- system.file("rawdata/test_data/test_clinical_data.xlsx", package = "RNAsum")
  (d <- clinical_info_read(x))
  expect_equal(colnames(d)[1], "Subject.ID")
  expect_null(clinical_info_read(NULL))
})

