# Generated by roxytest: Do not edit by hand!

# File R/salmon.R: @testexamples

test_that("Function salmon_counts() @ L15", {
  
  x <- system.file("rawdata/test_data/dragen/TEST.quant.sf", package = "RNAsum")
  tx2gene <- NULL
  (sc <- salmon_counts(x, tx2gene)) # NULL since no tx2gene specified
  expect_null(sc)
})

