# Generated by roxytest: do not edit by hand!

# File R/sample_data.R: @testexamples

test_that("Function read_sample_data() @ L36", {
  
  p <- list(
    dragen_rnaseq = system.file("rawdata/test_data/dragen", package = "RNAsum"),
    arriba_pdf = system.file("rawdata/test_data/dragen/arriba/fusions.pdf", package = "RNAsum"),
    arriba_tsv = system.file("rawdata/test_data/dragen/arriba/fusions.tsv", package = "RNAsum"),
    dragen_fusions = system.file(
      "rawdata/test_data/dragen/test_sample_WTS.fusion_candidates.final",
      package = "RNAsum"
    ),
    umccrise = system.file(
      "rawdata/test_data/umccrised/test_sample_WGS",
      package = "RNAsum"
    ),
    manta_tsv = system.file(
      "rawdata/test_data/umccrised/test_sample_WGS/structural/manta.tsv",
      package = "RNAsum"
    )
  )
  res <- read_sample_data(p, tempdir())
  expect_equal(length(res), 6)
  expect_null(res$salmon)
})


test_that("Function read_wgs_data() @ L80", {
  
  p <- list(
    umccrise = system.file("rawdata/test_data/umccrised/test_sample_WGS", package = "RNAsum"),
    pcgr_tiers_tsv = system.file(
      "rawdata/test_data/umccrised/test_sample_WGS/small_variants",
      "TEST-somatic.pcgr.snvs_indels.tiers.tsv",
      package = "RNAsum"
    ),
    manta_tsv = system.file(
      "rawdata/test_data/umccrised/test_sample_WGS/structural/TEST-prioritize-manta.tsv",
      package = "RNAsum"
    )
  )
  (res <- read_wgs_data(p))
  expect_equal(length(res), 3)
})

