# Generated by roxytest: do not edit by hand!

# File R/kallisto.R: @testexamples

test_that("Function kallisto_counts() @ L15", {
  
  x <- system.file("rawdata/test_data/quant/abundance.tsv", package = "RNAsum")
  tx2gene <- NULL
  (kc <- kallisto_counts(x, tx2gene)) # NULL since no tx2gene specified
  expect_null(sc)
})

