# Generated by roxytest: do not edit by hand!

# File R/pcgr.R: @testexamples

test_that("Function pcgr_tiers_tsv_read() @ L17", {
  
  x <- system.file(
    "rawdata/test_data/umccrised/test_sample_WGS/small_variants",
    "TEST-somatic.pcgr.snvs_indels.tiers.tsv",
    package = "RNAsum"
  )
  (ptsv <- pcgr_tiers_tsv_read(x))
  expect_null(pcgr_tiers_tsv_read(x = NULL))
})

