# Generated by roxytest: Do not edit by hand!

# File R/dragen_fusions.R: @testexamples

test_that("Function dragen_fusions_read() @ L17", {
  
  x <- system.file("rawdata/test_data/dragen",
    "test_sample_WTS.fusion_candidates.final",
    package = "RNAsum"
  )
  (a <- dragen_fusions_read(x))
  expect_equal(colnames(a)[ncol(a)], "ReadNames")
  expect_equal(colnames(a)[1], "gene1")
  expect_null(dragen_fusions_read(NULL))
})

