# Generated by roxytest: Do not edit by hand!

# File R/arriba_plots.R: @testexamples

test_that("Function arriba_tsv_read() @ L14", {
  
  x <- system.file("rawdata/test_data/dragen/arriba/fusions.tsv", package = "RNAsum")
  (a <- arriba_tsv_read(x))
  expect_equal(colnames(a)[ncol(a)], "read_identifiers")
})

