# usage: conda env create -p $(pwd)/miniconda/envs/rnasum --file environment.yaml 
# -p flag should point to your miniconda installation path.

# name of the conda environment
name: rnasum

#the paths that conda takes a look for packages. 
#avoid using anaconda as we have experienced issues with it
channels:
        - conda-forge
        - bioconda
        - plotly
        - defaults

#install following packages in the conda environment
dependencies:
        - libiconv
        - plotly-orca
        - pandoc
        - libopenblas==0.3.7
        - awscli
