package:
  name: r-rnasum
  version: 2.0.3.9000 # bump

source:
  path: ../../../

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - git
  host:
    - r-base >=4.3,<4.6
    - r-assertthat
    - r-conflicted
    - r-dplyr
    - r-dt
    - bioconductor-edaseq
    - bioconductor-edger
    - r-fs
    - r-ggforce
    - r-ggplot2
    - r-glue
    - r-here
    - r-htmltools
    - r-htmlwidgets
    - r-knitr
    - bioconductor-limma
    - r-matrixstats
    - r-optparse
    - r-pdftools
    - r-png
    - r-plotly
    - bioconductor-preprocesscore
    - r-purrr
    - r-ragg
    - r-rcircos
    - r-readr
    - r-rlang
    - r-rmarkdown
    - umccr::r-rnasum.data
    - r-scales
    - r-sessioninfo
    - r-stringr
    - r-tibble
    - r-tidyr
    - bioconductor-tximport
  run:
    - r-base >=4.3,<4.6
    - r-assertthat
    - r-conflicted
    - r-dplyr
    - r-dt
    - bioconductor-edaseq
    - bioconductor-edger
    - r-fs
    - r-ggforce
    - r-ggplot2
    - r-glue
    - r-here
    - r-htmltools
    - r-htmlwidgets
    - r-knitr
    - bioconductor-limma
    - r-matrixstats
    - r-optparse
    - r-pdftools
    - r-png
    - r-plotly
    - bioconductor-preprocesscore
    - r-purrr
    - r-ragg
    - r-rcircos
    - r-readr
    - r-rlang
    - r-rmarkdown
    - umccr::r-rnasum.data
    - r-scales
    - r-sessioninfo
    - r-stringr
    - r-tibble
    - r-tidyr
    - bioconductor-tximport

test:
  commands:
    - $R -e "library('RNAsum')"

about:
  home: https://github.com/umccr/RNAsum
  license: MIT + file LICENSE
  summary: RNAseq-based cancer patient reports
  license_family: MIT
