name: build-docker-container-and-push-to-ghcrio

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e v1.0, v20.15.10 etc
    - 'pre-v*' # Push events to matching pre-v, i.ve pre-v1.0, pre-v20.15.10

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Standard checkout step
      - name: Checkout code
        id: git_checkout
        uses: actions/checkout@v3
      # Get tag name, from /ref/heads/<tag> to <tag>
      - name: Get Tag Name
        id: get_tag_name
        run: echo "::set-output name=tag_name::$(basename ${{ github.ref }})"
      # Get repository name in lower
      - name: get lowercase repo name
        id: get_lowercase_repo_name
        run: echo "::set-output name=repo_name::$(tr '[:upper:]' '[:lower:]' <<< "${{ github.repository }}")"
      # Use qemu to perform multiplatform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # Use docker buildx to build multi-platform containers
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          use: true
          install: true
          config-inline: |
            [worker.oci]
              max-parallelism = 2
      # Log in to GitHub Container registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Build and push docker images
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: envm/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ steps.get_lowercase_repo_name.outputs.repo_name }}:${{ steps.get_tag_name.outputs.tag_name }}
